CREATE DATABASE IF NOT EXISTS Vigil_DB;

CREATE USER 'vigil'@'localhost' IDENTIFIED BY '';
GRANT SELECT, INSERT, UPDATE, DELETE ON Vigil_DB.* TO 'vigil'@'localhost';
FLUSH PRIVILEGES;

USE Vigil_DB;

CREATE TABLE IF NOT EXISTS Agents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(45) NOT NULL UNIQUE,
    last_heard_time DATETIME
);

CREATE TABLE IF NOT EXISTS Alerts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ingest_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_id INT NOT NULL,
    alert_time DATETIME NOT NULL,
    message TEXT,
    ack BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (agent_id) REFERENCES Agents(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AlertsArchive (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  original_alert_id INT NOT NULL,
  agent_ip VARCHAR(45) NOT NULL,
  time DATETIME NOT NULL,
  message TEXT,
  ingest_time DATETIME,
  archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);