---
- hosts: firewall
  connection: local
  remote_user: admin
  gather_facts: no

  vars:
    external_ip_address: "172.31.41.2/29"
    provider:
      ip_address: "192.168.1.41"
      password: "Changeme!"
      port: 443
      username: "admin"

  
  tasks:
    - name: Create Allow-Ping Management Profile
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ provider }}'
        name: 'Allow-Ping'
        ping: true
        permitted_ip: ['172.20.240.0/24', '172.20.241.0/24', '172.20.242.0/24']

    - name: Create Allow-HTTPS-SSH-Ping Management Profile
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ provider }}'
        name: 'Allow-HTTPS-SSH-Ping'
        https: true
        ssh: true
        ping: true
        permitted_ip: ['172.20.242.0/24']

    - name: Create Nothing Management Profile
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ provider }}'
        name: 'Nothing'

    - name: Commit Changes
      paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ provider }}' 

    - name: Set Ethernet1/1 (PUBLIC) Management Profile
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/1"
        zone_name: "Public"
        management_profile: "Allow-Ping"
        ip: "172.20.241.254/24"
        enable_dhcp: false
        comment: "Public"
        state: replaced

    - name: Set Ethernet1/2 (INTERNAL) Management Profile
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/2"
        zone_name: "Internal"
        management_profile: "Allow-Ping"
        ip: "172.20.240.254/24"
        enable_dhcp: false
        comment: "Internal"
        state: replaced

    - name: Set Ethernet1/3 (EXTERNAL) Management Profile
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/3"
        zone_name: "External"
        management_profile: "Nothing"
        ip: '{{ external_ip_address }}'
        enable_dhcp: false
        comment: "External"
        state: replaced

    - name: Set Ethernet1/4 (USER) Management Profile
      paloaltonetworks.panos.panos_interface:
        provider: '{{ provider }}'
        if_name: "ethernet1/4"
        zone_name: "User"
        management_profile: "Allow-HTTPS-SSH-Ping"
        ip: "172.20.242.254/24"
        enable_dhcp: false
        comment: "User"
        state: replaced



