---
- hosts: firewall
  connection: local
  remote_user: admin
  gather_facts: no

  vars:
    provider:
      api_key: "LUFRPT15bnBiVGpjcisvb2djYUEwSTlxanlDR1orR2s9MEJGb1J6NDNPc1pZeElneWRicTA3cHRtWHEzeGNPdkJvUjRNeE9takRMR3dtWXVLMWh3OXJnQkdQS0xKeW9SMg=="
      ip_address: "192.168.1.41"
      password: "Changeme!"
      port: 443
      username: "admin"
  
  tasks:
    - name: retrieve api key
      paloaltonetworks.panos.panos_api_key:
        provider: '{{ provider }}'

    - name: Create any2any rule
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'any2any test'
        description: 'Allow all traffic'
        source_zone: ['External', 'Internal', 'User', 'Public']
        source_ip: ['any']
        destination_zone: ['External', 'Internal', 'User', 'Public']
        destination_ip: ['any']
        application: ['any']
        action: 'allow'

