---
- hosts: firewall
  connection: local
  remote_user: admin
  gather_facts: no

  vars:
    passwd: "Password123!"
    provider:
      ip_address: "192.168.1.41"
      password: "Changeme!"
      port: 443
      username: "admin"

  
  tasks:
    - name: Set admin password
      paloaltonetworks.panos.panos_administrator:
        provider: '{{ provider }}'
        admin_username: 'admin'
        admin_password: '{{ passwd }}'
        superuser: true

    - name: Commit password changes
      paloaltonetworks.panos.panos_commit_firewall:
        provider '{{ provider }}'

